### ISSUE TITLE
Add testing and content generation commands

### ISSUE THREAD

**Issue by axellabs** [HubSpot/hubspot-cli#181]
For the past few weeks, I've been working on a small utility to generate pages and run automated tests on them. I think it could be useful to integrate that functionality into this app. 

Testing functions:
- generate sample pages out of templates
- test site updates with visual regressions
- generate blog posts and sample content automatically (referenced in https://github.com/HubSpot/hubspot-cms-tools/issues/38)
- delete test pages

[Link to repo of testing utility](https://git.hubteam.com/HubSpot/DesignAssetsAcceptanceTesting)

@ckconant @levinkeo

**Comment by axellabs** [comment]
@gcorne

**Comment by gcorne** [comment]
I think we should start with content generation. @axellabs is this something that you are planning to work on? If so, maybe we can discuss on Slack.

One thing that will need to be done before we release broadly is adjust personal access keys to add support for the `content` scope group so that the key can have permission to hit the blog and pages endpoints.

**Comment by axellabs** [comment]
I'm finishing up content generation this week! It exists for blog posts right now, and I'm adding a feature for websites. I can add you to that PR. 

I know a little about personal access keys but I'd love to talk more about adding them to this application.

**Comment by brandenrodgers** [comment]
Related: https://github.com/HubSpot/hubspot-cli/issues/38

**Comment by TanyaScales** [comment]
Closing this out as we have moved to an internal testing package for content assets
