### ISSUE TITLE
Add additional module skeletons to make it easier to build out a module locally

### ISSUE THREAD

**Issue by gcorne** [HubSpot/hubspot-cli#37]
The `Sample.module` that is created when running `hs create module` is super basic. What if we added a few more fleshed out modules that cover common scenarios like a module using a repeater or an image module.

@levinkeo @anthmatic @williamspiro

**Comment by TanyaScales** [comment]
Taking a look at the vast number of variations we could make here at this point due to editor improvements, field type additions etc. -- I'm going to close this out as autocomplete within fields.json files and updated, useful snippets that help with this type of scaffolding seem more fruitful to increasing developer efficiency when creating new modules and building them out.
