### ISSUE TITLE
Use environment variable for specifying config path

### ISSUE THREAD

**Issue by isaacl** [HubSpot/hubspot-cli#474]
I want to run hs without worrying about my current directory. Now I've solved this personally by adding an alias:
`zsh
echo "alias hs='hs -c ~/.config/hubspot.config.yml'" >> ~/.zshrc
`

But I think the proper fix is for hs to check for the presence of an env variable like `HUBSPOT_DEFAULT_CONFIG_PATH`, and if this env var is specified, `hs` should use it (`-c` should override the env var).

**Comment by anthmatic** [comment]
Hi @isaacl, thanks for filing this issue. The CLI actually supports a number of environment variables so while we don't support loading a config file this way, you can still create a global config.

These supported variables are available:
```  
portalId: HUBSPOT_PORTAL_ID
apiKey: HUBSPOT_API_KEY
Oauth client: HUBSPOT_CLIENT_ID
Oauth secret: HUBSPOT_CLIENT_SECRET
personalAccessKey: HUBSPOT_PERSONAL_ACCESS_KEY
```
and the `--use-env` flag can be added to your CLI command so that the environment variables will be used instead of looking up a config file.
