### ISSUE TITLE
10 vulnerabilities (5 moderate, 5 high) are found during installation

### ISSUE THREAD

**Issue by arinker** [HubSpot/hubspot-cli#593]
## Description and Context
While installing hubspot-cli via npm 10 vulnerabilities (5 moderate, 5 high) are found. caused by hubspot-cli

### Steps to reproduce
Add hubspot-cli to your project via ```npm install hubspot-cli --save-dev```.

## Expected behavior
No vulnerabilities should be found.

## Screenshots
<img width="574" alt="Bildschirmfoto 2021-11-10 um 09 43 30" src="https://user-images.githubusercontent.com/2835005/141080042-eb04802f-52ae-46c1-ad47-68bd5bfd5bd3.png">
<img width="573" alt="Bildschirmfoto 2021-11-10 um 09 43 51" src="https://user-images.githubusercontent.com/2835005/141080069-04e61395-9de5-4cb0-a6aa-7e2620acff24.png">

## Who to Notify
@arinker

**Comment by miketalley** [comment]
Hello @arinker and thanks for posing this issue! I'm going to take a look into this.

**Comment by arinker** [comment]
Thank you @miketalley!

**Comment by miketalley** [comment]
Several vulnerabilities have been fixed in #610. There are still some vulnerabilities in [lerna](https://github.com/lerna/lerna) and [spinnies](https://github.com/jcarpanelli/spinnies). There is a PR to fix the lerna vulnerabilities [here](https://github.com/lerna/lerna/pull/2986), and @anthmatic is going to work on a PR for spinnies to address those vulnerabilities.

Once those are merged, we can update our dependency versions to fix those.

**Comment by TanyaScales** [comment]
Closing out as the vulnerabilities mentioned here are no longer present
